#ifndef OPCODE_H
#define OPCODE_H
#define PUSH_FLOAT                      0x01
#define PUSH_STRING                     0x02
#define PUSH_TRUE                       0x03
#define PUSH_FALSE                      0x04
#define LOAD_NULL                       0x05
#define BINARY_ADD                      0x10
#define BINARY_SUB                      0x11
#define BINARY_MUL                      0x12
#define BINARY_DIV                      0x13
#define BINARY_BIGGER                   0x14
#define BINARY_SMALLER                  0x15
#define BINARY_EQUAL                    0x16
#define BINARY_NOT_EQUAL                0x17
#define BINARY_BIGGER_EQUAL             0x18
#define BINARY_SMALLER_EQUAL            0x19
#define AND_LOG                         0x1A
#define OR_LOG                          0x1B
#define NOT_LOG                         0x1C
#define POP_TOP                         0x20
#define PRINT                           0x21
#define LEN_OF                          0x22
#define BUILD_LIST                      0x23
#define LOAD_GLOBAL                     0x30
#define STORE_GLOBAL                    0x31
#define LOAD_LOCAL                      0x32
#define STORE_LOCAL                     0x33
#define LOAD_ITEM                       0x34
#define STORE_ITEM                      0x35
#define LOAD_ATTR                       0x36
#define STORE_ATTR                      0x37
#define LOAD_METHOD                     0x38
#define MAKE_FUNCTION                   0x40
#define START_FUNCTION                  0x41
#define END_FUNCTION                    0x42
#define MAKE_ARGS                       0x43
#define FUNCTION_CALL                   0x44
#define FUNCTION_CALL_VARARGS           0x45
#define RETURN_TOP                      0x46
#define MAKE_CLOSURE                    0x47
#define END_CLOSURE                     0x48
#define LOAD_CLOSURE                    0x49
#define STORE_CLOSURE                   0x4A
#define JUMP                            0x50
#define JUMP_FORWARD                    0x51
#define JUMP_BACKWARD                   0x52
#define JUMP_IF_TRUE                    0x53
#define JUMP_IF_FALSE                   0x54
#define POP_JUMP_IF_TRUE                0x55
#define POP_JUMP_IF_FALSE               0x56
#define JUMP_TO_N_TIMES                 0x57
#define LOOP_PREP                       0x58
#define LOOP_STEP                       0x59
#define START_BLOCK                     0x60
#define END_BLOCK                       0x61
#define CLASS_BEGIN                     0x62
#define CLASS_END                       0x63
#define SET_SUPER_CLASS                 0x64
#define PROGRAM_START                   0x70
#define PROGRAM_END                     0x71
#define EXIT_PROGRAM                    0x72
#define STOP_PROGRAM                    0x73
#define SKIP                            0x7F
#define LOAD_TRUE                       0x80
#define LOAD_FALSE                      0x81
#define JUMP_TO                         0x82
#define ADD_LABEL                       0x83
#define BINARY_MOD                      0x84
#endif // OPCODE_H